// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekdombinciwslxiloimi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZG9tYmluY2l3c2x4aWxvaW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTI2MDIsImV4cCI6MjA2NjQ4ODYwMn0.Z4bUc6THdLDsxvYVF5kwdRykETCJrx4dQAhb--nSXb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});