// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lonffjtvzlvqamyaejlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvbmZmanR2emx2cWFteWFlamxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDg5NjYsImV4cCI6MjA2NjM4NDk2Nn0.wpxR2rysleNX1T6_2MHcrAri8t9V0SeFRgryohRzx1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});